name: myaplication
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  build_runner: ^2.4.13
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  get_it: ^8.0.0
  go_router: ^14.2.8
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  talker: ^4.4.1
  talker_flutter: ^4.4.1
  talker_dio_logger: ^4.4.1
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
