// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYmkt-JMJzG19ZFMNZHNpsaSOgM6-E9pk',
    appId: '1:764556583689:web:66a90aca4ae64e7a9069d8',
    messagingSenderId: '764556583689',
    projectId: 'flutter-1819c',
    authDomain: 'flutter-1819c.firebaseapp.com',
    storageBucket: 'flutter-1819c.firebasestorage.app',
    measurementId: 'G-M30H5MPZ92',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6UPhs2IcdJTeY4kkj-lCwJ-r9NMwZXq0',
    appId: '1:764556583689:android:cf0a7a7fe89ccd6d9069d8',
    messagingSenderId: '764556583689',
    projectId: 'flutter-1819c',
    storageBucket: 'flutter-1819c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvIPETdZuTKyA8DdDrUFJ-Fws1PmN6WZU',
    appId: '1:764556583689:ios:56610d4d05301c3b9069d8',
    messagingSenderId: '764556583689',
    projectId: 'flutter-1819c',
    storageBucket: 'flutter-1819c.firebasestorage.app',
    iosBundleId: 'dshero',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvIPETdZuTKyA8DdDrUFJ-Fws1PmN6WZU',
    appId: '1:764556583689:ios:56610d4d05301c3b9069d8',
    messagingSenderId: '764556583689',
    projectId: 'flutter-1819c',
    storageBucket: 'flutter-1819c.firebasestorage.app',
    iosBundleId: 'dshero',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYmkt-JMJzG19ZFMNZHNpsaSOgM6-E9pk',
    appId: '1:764556583689:web:a5efdaef69ad6fb29069d8',
    messagingSenderId: '764556583689',
    projectId: 'flutter-1819c',
    authDomain: 'flutter-1819c.firebaseapp.com',
    storageBucket: 'flutter-1819c.firebasestorage.app',
    measurementId: 'G-M5RYDXPWLT',
  );
}
